name: Build, Package, and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  
      
      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build with musl
        run: |
          export CC=/usr/bin/musl-gcc
          go build --ldflags '-linkmode external -extldflags "-static"' -tags musl -o kafka-producer

      - name: Package artifact
        run: |
          mkdir -p dist
          cp kafka-producer dist/
          tar -czvf kafka-producer-linux-amd64.tar.gz -C dist .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kafka-producer-linux-amd64
          path: kafka-producer-linux-amd64.tar.gz

  release:
    needs: build  
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: kafka-producer-linux-amd64
          path: dist
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          tag_name: ${{ github.ref_name }}  
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  
          asset_path: ./dist/kafka-producer-linux-amd64.tar.gz
          asset_name: kafka-producer-linux-amd64.tar.gz
          asset_content_type: application/gzip